#!/bin/sh

set -x
rm -f Makefile Makefile.in aclocal.m4 config.h config.h.in  
rm -f configure config.status config.log stamp-h stamp-h.in
rm -rf autom4te.cache

aclocal -I config
autoheader
automake --add-missing --copy
autoconf
