#!/bin/sh
set -x

CLEAN_FILES="\
Makefile.in \
aclocal.m4 \
config.h.in \
configure \
etc/Makefile.in \
man/Makefile.in \
src/Makefile.in \
"
CLEAN_DIRS="\
autom4te.cache \
config \
"

rm -f $CLEAN_FILES
rm -rf $CLEAN_DIRS

autoreconf -i

